POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Pedro",
    "email": "pedro@gmail.com",
    "password": "1234567"
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "pedro@gmail.com",
    "password": "1234567"
}